
/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of AllExercisesResponse
 *
 * @constructor
 */
AllExercisesResponse = function (obj) {
    if(!obj) {
        this.name = null;     
        this.caloryCount = null;     
        this.category = null;     
        this.cardioSubcategory = null;     
        this.primaryMuscleGroup = null;     
        this.excerciseId = null;     
        //Append to variable dictionary
        this._variableDict['caloryCount'] = 'calory_count';
        this._variableDict['cardioSubcategory'] = 'cardio_subcategory';
        this._variableDict['primaryMuscleGroup'] = 'primary_muscle_group';
        this._variableDict['excerciseId'] = 'excercise_id';
    } else {
        this.name = (obj.name !== undefined && obj.name !== null)? obj.name : null;
        this.caloryCount = (obj.calory_count !== undefined && obj.calory_count !== null)? obj.calory_count : null;
        this.category = (obj.category !== undefined && obj.category !== null)? obj.category : null;
        this.cardioSubcategory = (obj.cardio_subcategory !== undefined && obj.cardio_subcategory !== null)? obj.cardio_subcategory : null;
        this.primaryMuscleGroup = (obj.primary_muscle_group !== undefined && obj.primary_muscle_group !== null)? obj.primary_muscle_group : null;
        this.excerciseId = (obj.excercise_id !== undefined && obj.excercise_id !== null)? obj.excercise_id : null;
        //Append to variable dictionary
        this._variableDict['caloryCount'] = 'calory_count';
        this._variableDict['cardioSubcategory'] = 'cardio_subcategory';
        this._variableDict['primaryMuscleGroup'] = 'primary_muscle_group';
        this._variableDict['excerciseId'] = 'excercise_id';
    }
};

AllExercisesResponse.prototype = new BaseModel();
AllExercisesResponse.prototype.constructor = AllExercisesResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AllExercisesResponse.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string} value 
 */
AllExercisesResponse.prototype.setName = function(value) {
    this.name = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AllExercisesResponse.prototype.getCaloryCount = function() {
    return this.caloryCount;
};

/**
 * Setter for CaloryCount
 * 
 * @param {string} value 
 */
AllExercisesResponse.prototype.setCaloryCount = function(value) {
    this.caloryCount = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AllExercisesResponse.prototype.getCategory = function() {
    return this.category;
};

/**
 * Setter for Category
 * 
 * @param {string} value 
 */
AllExercisesResponse.prototype.setCategory = function(value) {
    this.category = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AllExercisesResponse.prototype.getCardioSubcategory = function() {
    return this.cardioSubcategory;
};

/**
 * Setter for CardioSubcategory
 * 
 * @param {string} value 
 */
AllExercisesResponse.prototype.setCardioSubcategory = function(value) {
    this.cardioSubcategory = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AllExercisesResponse.prototype.getPrimaryMuscleGroup = function() {
    return this.primaryMuscleGroup;
};

/**
 * Setter for PrimaryMuscleGroup
 * 
 * @param {string} value 
 */
AllExercisesResponse.prototype.setPrimaryMuscleGroup = function(value) {
    this.primaryMuscleGroup = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AllExercisesResponse.prototype.getExcerciseId = function() {
    return this.excerciseId;
};

/**
 * Setter for ExcerciseId
 * 
 * @param {string} value 
 */
AllExercisesResponse.prototype.setExcerciseId = function(value) {
    this.excerciseId = value;
};


module.exports = AllExercisesResponse;
