
/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of AllFoodBrandsResponse
 *
 * @constructor
 */
AllFoodBrandsResponse = function (obj) {
    if(!obj) {
        this.brandName = null;     
        this.foodBrandId = null;     
        //Append to variable dictionary
        this._variableDict['brandName'] = 'brand_name';
        this._variableDict['foodBrandId'] = 'food_brand_id';
    } else {
        this.brandName = (obj.brand_name !== undefined && obj.brand_name !== null)? obj.brand_name : null;
        this.foodBrandId = (obj.food_brand_id !== undefined && obj.food_brand_id !== null)? obj.food_brand_id : null;
        //Append to variable dictionary
        this._variableDict['brandName'] = 'brand_name';
        this._variableDict['foodBrandId'] = 'food_brand_id';
    }
};

AllFoodBrandsResponse.prototype = new BaseModel();
AllFoodBrandsResponse.prototype.constructor = AllFoodBrandsResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AllFoodBrandsResponse.prototype.getBrandName = function() {
    return this.brandName;
};

/**
 * Setter for BrandName
 * 
 * @param {string} value 
 */
AllFoodBrandsResponse.prototype.setBrandName = function(value) {
    this.brandName = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AllFoodBrandsResponse.prototype.getFoodBrandId = function() {
    return this.foodBrandId;
};

/**
 * Setter for FoodBrandId
 * 
 * @param {string} value 
 */
AllFoodBrandsResponse.prototype.setFoodBrandId = function(value) {
    this.foodBrandId = value;
};


module.exports = AllFoodBrandsResponse;
