
/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of AllFoodRestaurantsResponse
 *
 * @constructor
 */
AllFoodRestaurantsResponse = function (obj) {
    if(!obj) {
        this.restaurantName = null;     
        this.foodRestaurantId = null;     
        //Append to variable dictionary
        this._variableDict['restaurantName'] = 'restaurant_name';
        this._variableDict['foodRestaurantId'] = 'food_restaurant_id';
    } else {
        this.restaurantName = (obj.restaurant_name !== undefined && obj.restaurant_name !== null)? obj.restaurant_name : null;
        this.foodRestaurantId = (obj.food_restaurant_id !== undefined && obj.food_restaurant_id !== null)? obj.food_restaurant_id : null;
        //Append to variable dictionary
        this._variableDict['restaurantName'] = 'restaurant_name';
        this._variableDict['foodRestaurantId'] = 'food_restaurant_id';
    }
};

AllFoodRestaurantsResponse.prototype = new BaseModel();
AllFoodRestaurantsResponse.prototype.constructor = AllFoodRestaurantsResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AllFoodRestaurantsResponse.prototype.getRestaurantName = function() {
    return this.restaurantName;
};

/**
 * Setter for RestaurantName
 * 
 * @param {string} value 
 */
AllFoodRestaurantsResponse.prototype.setRestaurantName = function(value) {
    this.restaurantName = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AllFoodRestaurantsResponse.prototype.getFoodRestaurantId = function() {
    return this.foodRestaurantId;
};

/**
 * Setter for FoodRestaurantId
 * 
 * @param {string} value 
 */
AllFoodRestaurantsResponse.prototype.setFoodRestaurantId = function(value) {
    this.foodRestaurantId = value;
};


module.exports = AllFoodRestaurantsResponse;
