
/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of AllLabTestsResponse
 *
 * @constructor
 */
AllLabTestsResponse = function (obj) {
    if(!obj) {
        this.labTestName = null;     
        this.alternateName = null;     
        this.labTestId = null;     
        this.labTestData = null;     
        //Append to variable dictionary
        this._variableDict['labTestName'] = 'lab_test_name';
        this._variableDict['alternateName'] = 'alternate_name';
        this._variableDict['labTestId'] = 'lab_test_id';
        this._variableDict['labTestData'] = 'lab_test_data';
    } else {
        this.labTestName = (obj.lab_test_name !== undefined && obj.lab_test_name !== null)? obj.lab_test_name : null;
        this.alternateName = (obj.alternate_name !== undefined && obj.alternate_name !== null)? obj.alternate_name : null;
        this.labTestId = (obj.lab_test_id !== undefined && obj.lab_test_id !== null)? obj.lab_test_id : null;
        this.labTestData = (obj.lab_test_data !== undefined && obj.lab_test_data !== null)? new LabTestData34(obj.lab_test_data) : null;
        //Append to variable dictionary
        this._variableDict['labTestName'] = 'lab_test_name';
        this._variableDict['alternateName'] = 'alternate_name';
        this._variableDict['labTestId'] = 'lab_test_id';
        this._variableDict['labTestData'] = 'lab_test_data';
    }
};

AllLabTestsResponse.prototype = new BaseModel();
AllLabTestsResponse.prototype.constructor = AllLabTestsResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AllLabTestsResponse.prototype.getLabTestName = function() {
    return this.labTestName;
};

/**
 * Setter for LabTestName
 * 
 * @param {string} value 
 */
AllLabTestsResponse.prototype.setLabTestName = function(value) {
    this.labTestName = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AllLabTestsResponse.prototype.getAlternateName = function() {
    return this.alternateName;
};

/**
 * Setter for AlternateName
 * 
 * @param {string} value 
 */
AllLabTestsResponse.prototype.setAlternateName = function(value) {
    this.alternateName = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AllLabTestsResponse.prototype.getLabTestId = function() {
    return this.labTestId;
};

/**
 * Setter for LabTestId
 * 
 * @param {string} value 
 */
AllLabTestsResponse.prototype.setLabTestId = function(value) {
    this.labTestId = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {LabTestData34}
 */
AllLabTestsResponse.prototype.getLabTestData = function() {
    return this.labTestData;
};

/**
 * Setter for LabTestData
 * 
 * @param {LabTestData34} value 
 */
AllLabTestsResponse.prototype.setLabTestData = function(value) {
    this.labTestData = value;
};


module.exports = AllLabTestsResponse;
