
/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of AllManufacturersResponse
 *
 * @constructor
 */
AllManufacturersResponse = function (obj) {
    if(!obj) {
        this.manufacturerId = null;     
        this.name = null;     
        //Append to variable dictionary
        this._variableDict['manufacturerId'] = 'manufacturer_id';
    } else {
        this.manufacturerId = (obj.manufacturer_id !== undefined && obj.manufacturer_id !== null)? obj.manufacturer_id : null;
        this.name = (obj.name !== undefined && obj.name !== null)? obj.name : null;
        //Append to variable dictionary
        this._variableDict['manufacturerId'] = 'manufacturer_id';
    }
};

AllManufacturersResponse.prototype = new BaseModel();
AllManufacturersResponse.prototype.constructor = AllManufacturersResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
AllManufacturersResponse.prototype.getManufacturerId = function() {
    return this.manufacturerId;
};

/**
 * Setter for ManufacturerId
 * 
 * @param {int} value 
 */
AllManufacturersResponse.prototype.setManufacturerId = function(value) {
    this.manufacturerId = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AllManufacturersResponse.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string} value 
 */
AllManufacturersResponse.prototype.setName = function(value) {
    this.name = value;
};


module.exports = AllManufacturersResponse;
