
/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of CommonSideEffectsResponse
 *
 * @constructor
 */
CommonSideEffectsResponse = function (obj) {
    if(!obj) {
        this.generic = null;     
        this.sideEffects = null;     
        //Append to variable dictionary
        this._variableDict['sideEffects'] = 'side_effects';
    } else {
        this.generic = (obj.generic !== undefined && obj.generic !== null)? obj.generic : null;
        this.sideEffects = (obj.side_effects !== undefined && obj.side_effects !== null)? obj.side_effects.map(function(model){
            return new SideEffect(model);
        }) : null;
        //Append to variable dictionary
        this._variableDict['sideEffects'] = 'side_effects';
    }
};

CommonSideEffectsResponse.prototype = new BaseModel();
CommonSideEffectsResponse.prototype.constructor = CommonSideEffectsResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
CommonSideEffectsResponse.prototype.getGeneric = function() {
    return this.generic;
};

/**
 * Setter for Generic
 * 
 * @param {string} value 
 */
CommonSideEffectsResponse.prototype.setGeneric = function(value) {
    this.generic = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
CommonSideEffectsResponse.prototype.getSideEffects = function() {
    return this.sideEffects;
};

/**
 * Setter for SideEffects
 * 
 * @param {array} value 
 */
CommonSideEffectsResponse.prototype.setSideEffects = function(value) {
    this.sideEffects = value;
};


module.exports = CommonSideEffectsResponse;
