
/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of Constituent
 *
 * @constructor
 */
Constituent = function (obj) {
    if(!obj) {
        this.name = null;     
        this.strength = null;     
    } else {
        this.name = (obj.name !== undefined && obj.name !== null)? obj.name : null;
        this.strength = (obj.strength !== undefined && obj.strength !== null)? obj.strength : null;
    }
};

Constituent.prototype = new BaseModel();
Constituent.prototype.constructor = Constituent;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
Constituent.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string} value 
 */
Constituent.prototype.setName = function(value) {
    this.name = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
Constituent.prototype.getStrength = function() {
    return this.strength;
};

/**
 * Setter for Strength
 * 
 * @param {string} value 
 */
Constituent.prototype.setStrength = function(value) {
    this.strength = value;
};


module.exports = Constituent;
