
/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of FoodItemsByRestaurantResponse
 *
 * @constructor
 */
FoodItemsByRestaurantResponse = function (obj) {
    if(!obj) {
        this.itemName = null;     
        this.calories = null;     
        this.servingQty = null;     
        this.servingUnit = null;     
        this.foodItemId = null;     
        this.foodBrandId = null;     
        //Append to variable dictionary
        this._variableDict['itemName'] = 'item_name';
        this._variableDict['servingQty'] = 'serving_qty';
        this._variableDict['servingUnit'] = 'serving_unit';
        this._variableDict['foodItemId'] = 'food_item_id';
        this._variableDict['foodBrandId'] = 'food_brand_id';
    } else {
        this.itemName = (obj.item_name !== undefined && obj.item_name !== null)? obj.item_name : null;
        this.calories = (obj.calories !== undefined && obj.calories !== null)? obj.calories : null;
        this.servingQty = (obj.serving_qty !== undefined && obj.serving_qty !== null)? obj.serving_qty : null;
        this.servingUnit = (obj.serving_unit !== undefined && obj.serving_unit !== null)? obj.serving_unit : null;
        this.foodItemId = (obj.food_item_id !== undefined && obj.food_item_id !== null)? obj.food_item_id : null;
        this.foodBrandId = (obj.food_brand_id !== undefined && obj.food_brand_id !== null)? obj.food_brand_id : null;
        //Append to variable dictionary
        this._variableDict['itemName'] = 'item_name';
        this._variableDict['servingQty'] = 'serving_qty';
        this._variableDict['servingUnit'] = 'serving_unit';
        this._variableDict['foodItemId'] = 'food_item_id';
        this._variableDict['foodBrandId'] = 'food_brand_id';
    }
};

FoodItemsByRestaurantResponse.prototype = new BaseModel();
FoodItemsByRestaurantResponse.prototype.constructor = FoodItemsByRestaurantResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
FoodItemsByRestaurantResponse.prototype.getItemName = function() {
    return this.itemName;
};

/**
 * Setter for ItemName
 * 
 * @param {string} value 
 */
FoodItemsByRestaurantResponse.prototype.setItemName = function(value) {
    this.itemName = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
FoodItemsByRestaurantResponse.prototype.getCalories = function() {
    return this.calories;
};

/**
 * Setter for Calories
 * 
 * @param {int} value 
 */
FoodItemsByRestaurantResponse.prototype.setCalories = function(value) {
    this.calories = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {double}
 */
FoodItemsByRestaurantResponse.prototype.getServingQty = function() {
    return this.servingQty;
};

/**
 * Setter for ServingQty
 * 
 * @param {double} value 
 */
FoodItemsByRestaurantResponse.prototype.setServingQty = function(value) {
    this.servingQty = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
FoodItemsByRestaurantResponse.prototype.getServingUnit = function() {
    return this.servingUnit;
};

/**
 * Setter for ServingUnit
 * 
 * @param {string} value 
 */
FoodItemsByRestaurantResponse.prototype.setServingUnit = function(value) {
    this.servingUnit = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
FoodItemsByRestaurantResponse.prototype.getFoodItemId = function() {
    return this.foodItemId;
};

/**
 * Setter for FoodItemId
 * 
 * @param {string} value 
 */
FoodItemsByRestaurantResponse.prototype.setFoodItemId = function(value) {
    this.foodItemId = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
FoodItemsByRestaurantResponse.prototype.getFoodBrandId = function() {
    return this.foodBrandId;
};

/**
 * Setter for FoodBrandId
 * 
 * @param {string} value 
 */
FoodItemsByRestaurantResponse.prototype.setFoodBrandId = function(value) {
    this.foodBrandId = value;
};


module.exports = FoodItemsByRestaurantResponse;
