
/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of Item
 *
 * @constructor
 */
Item = function (obj) {
    if(!obj) {
        this.name = null;     
    } else {
        this.name = (obj.name !== undefined && obj.name !== null)? obj.name : null;
    }
};

Item.prototype = new BaseModel();
Item.prototype.constructor = Item;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
Item.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string} value 
 */
Item.prototype.setName = function(value) {
    this.name = value;
};


module.exports = Item;
