
/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of LabTestData34
 *
 * @constructor
 */
LabTestData34 = function (obj) {
    if(!obj) {
        this.orderingInformation = null;     
        this.laboratory = null;     
        this.testCode = null;     
        this.specimenTypes = null;     
        this.containerTypes = null;     
        this.collectionInstructions = null;     
        this.frequency = null;     
        //Append to variable dictionary
        this._variableDict['orderingInformation'] = 'Ordering information';
        this._variableDict['laboratory'] = 'Laboratory';
        this._variableDict['testCode'] = 'Test Code';
        this._variableDict['specimenTypes'] = 'Specimen types';
        this._variableDict['containerTypes'] = 'Container types';
        this._variableDict['collectionInstructions'] = 'Collection Instructions';
        this._variableDict['frequency'] = 'Frequency';
    } else {
        this.orderingInformation = (obj.Orderinginformation !== undefined && obj.Orderinginformation !== null)? obj.Orderinginformation : null;
        this.laboratory = (obj.Laboratory !== undefined && obj.Laboratory !== null)? obj.Laboratory : null;
        this.testCode = (obj.TestCode !== undefined && obj.TestCode !== null)? obj.TestCode : null;
        this.specimenTypes = (obj.Specimentypes !== undefined && obj.Specimentypes !== null)? obj.Specimentypes : null;
        this.containerTypes = (obj.Containertypes !== undefined && obj.Containertypes !== null)? obj.Containertypes : null;
        this.collectionInstructions = (obj.CollectionInstructions !== undefined && obj.CollectionInstructions !== null)? obj.CollectionInstructions : null;
        this.frequency = (obj.Frequency !== undefined && obj.Frequency !== null)? obj.Frequency : null;
        //Append to variable dictionary
        this._variableDict['orderingInformation'] = 'Ordering information';
        this._variableDict['laboratory'] = 'Laboratory';
        this._variableDict['testCode'] = 'Test Code';
        this._variableDict['specimenTypes'] = 'Specimen types';
        this._variableDict['containerTypes'] = 'Container types';
        this._variableDict['collectionInstructions'] = 'Collection Instructions';
        this._variableDict['frequency'] = 'Frequency';
    }
};

LabTestData34.prototype = new BaseModel();
LabTestData34.prototype.constructor = LabTestData34;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
LabTestData34.prototype.getOrderingInformation = function() {
    return this.orderingInformation;
};

/**
 * Setter for OrderingInformation
 * 
 * @param {string} value 
 */
LabTestData34.prototype.setOrderingInformation = function(value) {
    this.orderingInformation = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
LabTestData34.prototype.getLaboratory = function() {
    return this.laboratory;
};

/**
 * Setter for Laboratory
 * 
 * @param {string} value 
 */
LabTestData34.prototype.setLaboratory = function(value) {
    this.laboratory = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
LabTestData34.prototype.getTestCode = function() {
    return this.testCode;
};

/**
 * Setter for TestCode
 * 
 * @param {string} value 
 */
LabTestData34.prototype.setTestCode = function(value) {
    this.testCode = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
LabTestData34.prototype.getSpecimenTypes = function() {
    return this.specimenTypes;
};

/**
 * Setter for SpecimenTypes
 * 
 * @param {string} value 
 */
LabTestData34.prototype.setSpecimenTypes = function(value) {
    this.specimenTypes = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
LabTestData34.prototype.getContainerTypes = function() {
    return this.containerTypes;
};

/**
 * Setter for ContainerTypes
 * 
 * @param {string} value 
 */
LabTestData34.prototype.setContainerTypes = function(value) {
    this.containerTypes = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
LabTestData34.prototype.getCollectionInstructions = function() {
    return this.collectionInstructions;
};

/**
 * Setter for CollectionInstructions
 * 
 * @param {string} value 
 */
LabTestData34.prototype.setCollectionInstructions = function(value) {
    this.collectionInstructions = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
LabTestData34.prototype.getFrequency = function() {
    return this.frequency;
};

/**
 * Setter for Frequency
 * 
 * @param {string} value 
 */
LabTestData34.prototype.setFrequency = function(value) {
    this.frequency = value;
};


module.exports = LabTestData34;
