
/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of MedicineInteractionsResponse
 *
 * @constructor
 */
MedicineInteractionsResponse = function (obj) {
    if(!obj) {
        this.generic = null;     
        this.interactions = null;     
    } else {
        this.generic = (obj.generic !== undefined && obj.generic !== null)? obj.generic : null;
        this.interactions = (obj.interactions !== undefined && obj.interactions !== null)? obj.interactions.map(function(model){
            return new Interaction(model);
        }) : null;
    }
};

MedicineInteractionsResponse.prototype = new BaseModel();
MedicineInteractionsResponse.prototype.constructor = MedicineInteractionsResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
MedicineInteractionsResponse.prototype.getGeneric = function() {
    return this.generic;
};

/**
 * Setter for Generic
 * 
 * @param {string} value 
 */
MedicineInteractionsResponse.prototype.setGeneric = function(value) {
    this.generic = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
MedicineInteractionsResponse.prototype.getInteractions = function() {
    return this.interactions;
};

/**
 * Setter for Interactions
 * 
 * @param {array} value 
 */
MedicineInteractionsResponse.prototype.setInteractions = function(value) {
    this.interactions = value;
};


module.exports = MedicineInteractionsResponse;
