
/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of PopularUsageResponse
 *
 * @constructor
 */
PopularUsageResponse = function (obj) {
    if(!obj) {
        this.generic = null;     
        this.usages = null;     
    } else {
        this.generic = (obj.generic !== undefined && obj.generic !== null)? obj.generic : null;
        this.usages = (obj.usages !== undefined && obj.usages !== null)? obj.usages.map(function(model){
            return new Usage(model);
        }) : null;
    }
};

PopularUsageResponse.prototype = new BaseModel();
PopularUsageResponse.prototype.constructor = PopularUsageResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
PopularUsageResponse.prototype.getGeneric = function() {
    return this.generic;
};

/**
 * Setter for Generic
 * 
 * @param {string} value 
 */
PopularUsageResponse.prototype.setGeneric = function(value) {
    this.generic = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
PopularUsageResponse.prototype.getUsages = function() {
    return this.usages;
};

/**
 * Setter for Usages
 * 
 * @param {array} value 
 */
PopularUsageResponse.prototype.setUsages = function(value) {
    this.usages = value;
};


module.exports = PopularUsageResponse;
