
/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of RequestAccessTokenRequest
 *
 * @constructor
 */
RequestAccessTokenRequest = function (obj) {
    if(!obj) {
        this.grantType = null;     
        this.clientId = null;     
        this.clientSecret = null;     
        this.scope = null;     
        //Append to variable dictionary
        this._variableDict['grantType'] = 'grant_type';
        this._variableDict['clientId'] = 'client_id';
        this._variableDict['clientSecret'] = 'client_secret';
    } else {
        this.grantType = (obj.grant_type !== undefined && obj.grant_type !== null)? obj.grant_type : null;
        this.clientId = (obj.client_id !== undefined && obj.client_id !== null)? obj.client_id : null;
        this.clientSecret = (obj.client_secret !== undefined && obj.client_secret !== null)? obj.client_secret : null;
        this.scope = (obj.scope !== undefined && obj.scope !== null)? obj.scope : null;
        //Append to variable dictionary
        this._variableDict['grantType'] = 'grant_type';
        this._variableDict['clientId'] = 'client_id';
        this._variableDict['clientSecret'] = 'client_secret';
    }
};

RequestAccessTokenRequest.prototype = new BaseModel();
RequestAccessTokenRequest.prototype.constructor = RequestAccessTokenRequest;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RequestAccessTokenRequest.prototype.getGrantType = function() {
    return this.grantType;
};

/**
 * Setter for GrantType
 * 
 * @param {string} value 
 */
RequestAccessTokenRequest.prototype.setGrantType = function(value) {
    this.grantType = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RequestAccessTokenRequest.prototype.getClientId = function() {
    return this.clientId;
};

/**
 * Setter for ClientId
 * 
 * @param {string} value 
 */
RequestAccessTokenRequest.prototype.setClientId = function(value) {
    this.clientId = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RequestAccessTokenRequest.prototype.getClientSecret = function() {
    return this.clientSecret;
};

/**
 * Setter for ClientSecret
 * 
 * @param {string} value 
 */
RequestAccessTokenRequest.prototype.setClientSecret = function(value) {
    this.clientSecret = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
RequestAccessTokenRequest.prototype.getScope = function() {
    return this.scope;
};

/**
 * Setter for Scope
 * 
 * @param {string} value 
 */
RequestAccessTokenRequest.prototype.setScope = function(value) {
    this.scope = value;
};


module.exports = RequestAccessTokenRequest;
