
/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of Schedule
 *
 * @constructor
 */
Schedule = function (obj) {
    if(!obj) {
        this.category = null;     
        this.label = null;     
    } else {
        this.category = (obj.category !== undefined && obj.category !== null)? obj.category : null;
        this.label = (obj.label !== undefined && obj.label !== null)? obj.label : null;
    }
};

Schedule.prototype = new BaseModel();
Schedule.prototype.constructor = Schedule;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
Schedule.prototype.getCategory = function() {
    return this.category;
};

/**
 * Setter for Category
 * 
 * @param {string} value 
 */
Schedule.prototype.setCategory = function(value) {
    this.category = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
Schedule.prototype.getLabel = function() {
    return this.label;
};

/**
 * Setter for Label
 * 
 * @param {string} value 
 */
Schedule.prototype.setLabel = function(value) {
    this.label = value;
};


module.exports = Schedule;
