/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

var Configuration = {
    //The base Uri for API calls
    BASEURI : "http://{{0}}/api/v1",

    //TODO: Replace the Host with an appropriate value
    host : "TODO: Replace",

    //The OAuth 2.0 access token to be set before API calls
    //TODO: Replace the OAuthAccessToken with an appropriate value
    oAuthAccessToken : "TODO: Replace"

};

module.exports = Configuration;
