/**
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 *
 */
'use strict';


/**
 * Creates an instance of HttpResponse
 *
 * @constructor
 */
function HttpResponse() {
    this.statusCode = null;
    this.body = null;
    this.headers = null;
}

module.exports = HttpResponse;
