/**
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 *
 */
'use strict';


/**
 * Creates an instance of HttpContext.
 *
 * @constructor
 */
function HttpContext() {
    this.request = null;
    this.response = null;
}

module.exports = HttpContext;
